version: '3.8'
services:
  backend:
    image: imsongj/test_backend:latest
    build:
      context: ./backend/lighthouse
      dockerfile: Dockerfile

  frontend:
    image: imsongj/test_frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile